spring:
  profiles:
    active: local
  application:
    name: dataservice
  jpa:
    show-sql: true
    
#DATA MASTER PORT IS 2333 - SWAP THIS IN WHEN PUSHING TO MASTER
#DATA DEVELOPMENT PORT IS 1235 - THIS SHOULD BE ACTIVE BY DEFAULT    
    
server:
  port: 1235

---
spring:
  profiles: local
  datasource:
    platform: h2
    url: jdbc:h2:mem:project3;Mode=PostgreSQL;
    username: sa
    password: password    
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:      enabled: true
    
eureka:
  client:
    enabled: false

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    database: postgresql


#EUREKA MASTER PORT IS 2329 - SWAP THIS IN WHEN PUSHING TO MASTER
#EUREKA DEVELOPMENT PORT IS 8762 - THIS SHOULD BE ACTIVE BY DEFAULT

eureka:
  client:
    service-url:      defaultZone: http://ec2-3-235-74-191.compute-1.amazonaws.com:8762/eureka
  instance:
    prefer-ip-address: true
    ip-address: 3.235.74.191
